from snakemake.utils import validate


configfile: "config/config.yaml"


validate(config, schema="schemas/config.schema.yaml")


include: "rules/common.smk"


if CV_MODE:

    include: "rules/split.smk"
    include: "rules/plink.smk"
    include: "rules/fit.smk"
    include: "rules/post.smk"
    include: "rules/predict.smk"
    include: "rules/evaluate.smk"

    rule all:
        input:
            results("summary.tsv"),

else:

    include: "rules/full.smk"

    rule all:
        input:
            expand(results("{phenotype}/predictions.tsv"), phenotype=PHENOTYPES),
